event = "Team Round 11"
password = "zHaSz8to"
timezone = "America/Los_Angeles"

[[admin]]
username = "admin"
password = "aegis!@#"

[[image]]
name = "Server2022_TR11"
color = "#EE4266"

[[image]]
name = "Ubuntu22_TR10"
color = "#E6E6FA"

[[image]]
name = "Fedora36_TR11"
color = "#6eba82"

[[team]]
id = "testing_id"
alias = "testing_id"
email = "none@mail.com"


[[team]]
id = "e6bb6bae-34bd-41ee-bf3e-88a01491b5ad"
alias = "CyberAegisVitalis"
email = "Yash Parikh"

[[team]]
id = "3b6f151a-7cfb-4654-8303-6bd1dacbb36a"
alias = "CyberAegisAvian"
email = "Meena Atluri"

[[team]]
id = "13b49ef8-170e-4b0e-9330-f454b1484491"
alias = "CyberAegisSpark"
email = "Yash Patil"

[[team]]
id = "3c3e5fc6-1f0c-481b-9e60-da8e047ada75"
alias = "CyberAegisGenis"
email = "Aadithyaa Mohanraj"

[[team]]
id = "f5e89225-9254-4c71-b2fb-f0b934507fc8"
alias = "CyberAegisExos"
email = "Akshay Rohatgi"

[[team]]
id = "2c920b4c-4e64-4b77-94f4-8329ffe18376"
alias = "CyberAegisDrift"
email = "Aarav Arora"

[[team]]
id = "cd9688b2-f462-4732-a683-ed402053e90b"
alias = "CyberAegisAevus"
email = "Alex Lu"

[[team]]
id = "439ce244-1c29-423f-85d3-185acc0f9c1a"
alias = "CyberAegisAeris"
email = "Mihir Bapat"

[[team]]
id = "d0df5e74-9b19-427b-b09f-62d4b8e47892"
alias = "CyberAegisAstra"
email = "Nisa Thomas"

[[team]]
id = "d659d194-0554-46d6-a36d-eda3dc77e1cf"
alias = "CyberAegisFlo"
email = "Raiden Tung"

[[team]]
id = "7008f5bb-56e9-4cb7-a98e-ba5eb3f3a8fb"
alias = "CyberAegisHopper"
email = "Rachel Lee"

[[team]]
id = "6a73a226-e85d-44fb-a9ea-f890883734bf"
alias = "CyberAegisVigor"
email = "Srijan Atti"

[[team]]
id = "1ef08ffb-283f-4498-83ab-003b0f5d367b"
alias = "CyberAegisCryo"
email = "Travis Callow"

[[team]]
id = "44616738-3c23-4844-a3a4-a9f3668246ce"
alias = "CyberAegisAtax"
email = "Celine Wu"

[[team]]
id = "bfe43e92-912c-43d1-b6a8-f8ac21817a30"
alias = "CyberAegisInfernus"
email = "Steven Zhu"

[[team]]
id = "2e4ee8f6-cabe-44bf-b960-ac048ad181e5"
alias = "CyberAegisSpyte"
email = "Divyani Agarwal"

[[team]]
id = "d7426e0a-de40-4654-8252-678b0b887610"
alias = "CyberAegisVapore"
email = "Aadit Gupta"

[[team]]
id = "5ee811f3-2838-4101-8366-56d95b4889ef"
alias = "CyberAegisCyclonius"
email = "Declan Boyle"

[[team]]
id = "00d25fd1-bd14-47d3-9583-ee5bb9a62b92"
alias = "CyberAegisPebble"
email = "Arnav Pallapotu"

[[team]]
id = "f6bb684f-2792-4629-8c76-ac7ba01b53b6"
alias = "CyberAegisEntros"
email = "Meena Annamalai"

[[team]]
id = "95805ffd-17c3-4452-ad2f-6a52ac767fdd"
alias = "CyberAegisVolaris"
email = "Karthik Valluri"
